# -*- coding: utf-8 -*-
"""demoops_day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oASj-EG2FQZt41KoeAMTEdiyNbKYd9zu
"""

class Democlass:
  a=10

demoobject = Democlass()
print(demoobject.a)

class Democlass :
  def total(self):
    print(40+50)

demoobject = Democlass()
demoobject.total();

class Democlass:
  a=10
  def showvalue(self):
    print(a)

objectname=Democlass()
objectname.showvalue()

class Democlass:
  a=10
  def showvalue(self):
    print(self.a)

objectname=Democlass()
objectname.showvalue()

class Democlass:
  def showvalue(self,a,b):
    print(a+b)

objectname=Democlass()
objectname.showvalue(20,30)

"""#Constructor"""

class Democlass:
  def __init__(self):
    print("Welcome")

obj=Democlass()

"""#Inheritance"""

#Single Inheritance
class A:
  def HelpA(self):
    print("Welcome to A")

class B(A):
  def HelpB(self):
    print("Welcome to B")

obj=B()
obj.HelpA()
obj.HelpB()

#Multilevel Inheritance
class A:
  def HelpA(self):
    print("Welcome to A")

class B(A):
  def HelpB(self):
    print("Welcome to B")

class C(B):
  def HelpC(self):
    print("Welcome to C")


obj=C()
obj.HelpA()
obj.HelpB()
obj.HelpC()

class A:
  def displayA(self):
    print("welcome A")

class B:
  def displayB(self):
    print("welcome B")

class C(A,B):
  def displayC(self):
    print("welcome C")

obj=C()
obj.displayA()
obj.displayB()
obj.displayC()

"""#Encapsulation"""

class Employee:
  __name= "rashi"

obj = Employee()
print(obj.__name)

class employee:
  __name="rashi"
  def __init__(self):
    print(self.__name)

obj=employee()

"""#Polymorphism"""

#Overridding
class EN:
  def information(self, name =""):
    print("welcome to EN " + name)

obj =EN()
obj.information()
obj.information("Python")

#Overridding
class EN:
  def information(self):
    print("Welcome to EN")

class ACC(EN):
  def information(self):
    print("Welcome to ACC")

obj= ACC()
obj.information()

"""#Super Concept"""

class EN:
  def information(self):
    print("Welcome to EN")

class ACC(EN):
  def information(self):
    super().information()
    print("Welcome to ACC")

obj= ACC()
obj.information()

"""#Abstraction"""

from abc import ABC, abstractmethod

class Greet(ABC):
  @abstractmethod
  def say_hello(self):
    pass

class English(Greet):
  def say_hello(self):
    return("Hello!")

obj=English()
print(obj.say_hello())