# -*- coding: utf-8 -*-
"""Exception Handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Zgre5aQ3uFczO8_BEWWnmDwZmtGGtcs
"""

def divide(a, b):
    try:
        result = int(a) / int(b)
    except ValueError:
        print("Please enter numbers only.")
    except ZeroDivisionError:
        print("Cannot divide by zero.")
    else:
        print("Result:", result)
    finally:
        print("-- divide() finished --")

divide("10", "2")   # Result: 5.0
divide("10", "0")   # Cannot divide by zero.
divide("ten", "2")  # Please enter numbers only.

# Demo 3.3
# – raise built-in exceptions
def set_age(age):
  if not isinstance(age, int):
     raise TypeError("Age must be an integer")
  if age < 0:
    raise ValueError(f"Age cannot be negative: {age}")
  return age


for a in [25, -5, "abc"]:
  try:
    print("Age set to", set_age(a))
  except (ValueError, TypeError) as e:
     print("Rejected:", e)

